### ISSUE TITLE
Statesync not working on v0.10.20 

### ISSUE THREAD

**Issue by kiselev-sv** [bnb-chain/node#1020]
Running 0.10.20 with 
state_sync_height = 373514678
fast_sync = true
state_sync_reactor = true
hot_sync = true

have many
```
node-1  | I[2024-05-13|07:32:48.496] broadcast state status request               module=statesync 
node-1  | I[2024-05-13|07:32:48.515] added manifest                               module=statesync peer=5c96d4f0174dda7757bcda11a57ecc91851a90f0 manifestHash=c72a2ab14296ff1775d4b33c5f3dbe1eb7db0f36c364bcf93675514292be570e
node-1  | I[2024-05-13|07:32:48.516] added manifest                               module=statesync peer=ca1245471ff1f2224e1076dfd94d7d2d66077cf5 manifestHash=c72a2ab14296ff1775d4b33c5f3dbe1eb7db0f36c364bcf93675514292be570e
node-1  | I[2024-05-13|07:32:48.762] added manifest                               module=statesync peer=dbec1c96777dc757db67945cbc41e3e793b94261 manifestHash=9c7f9ec5700573f8706cf1f925af8de6e0037bce24d6ff2ffa2f8d4ca068a8e1
node-1  | I[2024-05-13|07:32:49.030] added manifest                               module=statesync peer=e2acf608686f830386e8648d6fc2f50c3316aa88 manifestHash=5472530a0faa5d7c321584426f5eb70d7afcdc6392d0e886a7d75523d92c080d
node-1  | I[2024-05-13|07:32:49.036] added manifest                               module=statesync peer=0fd066de431d13e5613aba53b3ed25c5a7a0b67c manifestHash=471e896ba2444148973784a77a70873cd35d0c2fbbd62bc0f8caa4c3f42db8dd
node-1  | I[2024-05-13|07:32:49.037] added manifest                               module=statesync peer=98579505572cc85488caa403bebb62e5b61d68e0 manifestHash=5472530a0faa5d7c321584426f5eb70d7afcdc6392d0e886a7d75523d92c080d
node-1  | I[2024-05-13|07:32:49.040] added manifest                               module=statesync peer=782303c9060d46211225662fdd1dd411c638263a manifestHash=471e896ba2444148973784a77a70873cd35d0c2fbbd62bc0f8caa4c3f42db8dd
node-1  | I[2024-05-13|07:32:49.579] added manifest                               module=statesync peer=b7affdf084115fd7e7cdbc04686ef8c218e1801c manifestHash=b3121e3396e32fd16e6462dc94d9314b279102acf49d3dbb247b740c23ef3269
node-1  | I[2024-05-13|07:32:58.497] decided not init pool                        module=statesync manifests=5 tried=215

```
but no sync

**Comment by DangVanSo** [comment]
node-1  | I[2024-05-13|07:32:48.496] broadcast state status request               module=statesync 
node-1  | I[2024-05-13|07:32:48.515] added manifest                               module=statesync peer=5c96d4f0174dda7757bcda11a57ecc91851a90f0 manifestHash=c72a2ab14296ff1775d4b33c5f3dbe1eb7db0f36c364bcf93675514292be570e
node-1  | I[2024-05-13|07:32:48.516] added manifest                               module=statesync peer=ca1245471ff1f2224e1076dfd94d7d2d66077cf5 manifestHash=c72a2ab14296ff1775d4b33c5f3dbe1eb7db0f36c364bcf93675514292be570e
node-1  | I[2024-05-13|07:32:48.762] added manifest                               module=statesync peer=dbec1c96777dc757db67945cbc41e3e793b94261 manifestHash=9c7f9ec5700573f8706cf1f925af8de6e0037bce24d6ff2ffa2f8d4ca068a8e1
node-1  | I[2024-05-13|07:32:49.030] added manifest                               module=statesync peer=e2acf608686f830386e8648d6fc2f50c3316aa88 manifestHash=5472530a0faa5d7c321584426f5eb70d7afcdc6392d0e886a7d75523d92c080d
node-1  | I[2024-05-13|07:32:49.036] added manifest                               module=statesync peer=0fd066de431d13e5613aba53b3ed25c5a7a0b67c manifestHash=471e896ba2444148973784a77a70873cd35d0c2fbbd62bc0f8caa4c3f42db8dd
node-1  | I[2024-05-13|07:32:49.037] added manifest                               module=statesync peer=98579505572cc85488caa403bebb62e5b61d68e0 manifestHash=5472530a0faa5d7c321584426f5eb70d7afcdc6392d0e886a7d75523d92c080d
node-1  | I[2024-05-13|07:32:49.040] added manifest                               module=statesync peer=782303c9060d46211225662fdd1dd411c638263a manifestHash=471e896ba2444148973784a77a70873cd35d0c2fbbd62bc0f8caa4c3f42db8dd
node-1  | I[2024-05-13|07:32:49.579] added manifest                               module=statesync peer=b7affdf084115fd7e7cdbc04686ef8c218e1801c manifestHash=b3121e3396e32fd16e6462dc94d9314b279102acf49d3dbb247b740c23ef3269
node-1  | I[2024-05-13|07:32:58.497] decided not init pool                        module=statesync manifests=5 tried=215
