### ISSUE TITLE
BNB node upgrade

### ISSUE THREAD

**Issue by mszczepanik1337** [bnb-chain/node#896]
Hi, i was trying to upgrade bnb node to 0.10.3v,  added 
BEP153Height = 284376000
BEP173Height = 284376000
to config but after restart ive got errors

I[2022-12-07|11:56:48.269] Starting ABCI with Tendermint                module=main 
panic: Unknown name bridge

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/store.(*rootMultiStore).nameToKey(0xc0001593b0, 0xc0090dfe20, 0x6, 0xc000c1e558, 0xc0000ab8d0)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.20/store/rootmultistore.go:379 +0x177
github.com/cosmos/cosmos-sdk/store.(*rootMultiStore).LoadVersion(0xc0001593b0, 0x10dbf5dd, 0x10dbf5dd, 0x1)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.20/store/rootmultistore.go:135 +0x4e8
github.com/cosmos/cosmos-sdk/store.(*rootMultiStore).LoadLatestVersion(0xc0001593b0, 0xc000c1eaa8, 0x2)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.20/store/rootmultistore.go:104 +0x4f
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).LoadCMSLatestVersion(...)
	/home/suyu/go/pkg/mod/github.com/binance-chain/bnc-cosmos-sdk@v0.25.0-binance.20/baseapp/baseapp.go:171
github.com/binance-chain/node/app.NewBinanceChain(0x19127a0, 0xc000e60ec0, 0x192b1c0, 0xc0000102e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100)
	/home/suyu/go/src/github.com/binance-chain/node/app/app.go:224 +0x1aba
main.newApp(0x19127a0, 0xc000e60ec0, 0x192b1c0, 0xc0000102e0, 0x0, 0x0, 0xc00036cb40, 0x55)

can someone help?

**Comment by Pythonberg1997** [comment]
Please post your `app.toml`

**Comment by Pythonberg1997** [comment]
Close the issue. Feel free to reopen it anytime you need.
