### ISSUE TITLE
Deleting old snapshots

### ISSUE THREAD

**Issue by Crypto2** [bnb-chain/node#900]
Is it safe to delete old snapshots from the data directory? Would be nice to free up that space.

**Comment by isaacyuno** [comment]
How's your snapshot folders look like? How many folders are there? Should be fine to delete

**Comment by Crypto2** [comment]
It has ~650 snapshot folders, one a day going back to early last year.

**Comment by isaacyuno** [comment]
Could delete those with old block numbers
