### ISSUE TITLE
Join testnet issue - incompatible: Peer is on a different network

### ISSUE THREAD

**Issue by sotatek-manhnguyen8** [bnb-chain/node#902]
Hello there,

I would like to run testnet fullnode with v0.10.3. I aso downloaded testnet_config.zip. All config is used with no change
But when starting, I got this error and node cannot start. 
Please help me check and resolve it

> I[2022-12-23|03:09:19.533] Starting ABCI with Tendermint                module=main 
E[2022-12-23|03:09:19.565] Failed to load the latest breathe block height from module=dexkeeper timeNow=2022-12-23T03:09:19.565740152Z
I[2022-12-23|03:09:19.565] Loading order book snapshot from last breathe block module=main blockHeight=0
I[2022-12-23|03:09:19.565] No breathe block is ever saved. just created match engines for all the pairs. module=main 
E[2022-12-23|03:09:19.566] Failed to load the latest breathe block height from module=dexkeeper timeNow=2022-12-23T03:09:19.566183608Z
I[2022-12-23|03:09:19.566] get last breathe block height                module=main height=0
E[2022-12-23|03:09:19.667] failed to load immutable tree                module=statesync err="version does not exist" store="KVStoreKey{0xc00001a600, acc}"
E[2022-12-23|03:09:19.837] Error dialing seed                           module=p2p err="incompatible: Peer is on a different network. Got Binance-Chain-Ganges, expected Binance-Chain-Nile" seed=9612b570bffebecca4776cb4512d08e252119005@3.114.127.147:27146
E[2022-12-23|03:09:20.838] Error dialing seed                           module=p2p err="dial tcp 52.198.111.20:27146: i/o timeout" seed=7156d461742e2a1e569fd68426009c4194830c93@52.198.111.20:27146
E[2022-12-23|03:09:21.056] Error dialing seed                           module=p2p err="incompatible: Peer is on a different network. Got Binance-Chain-Ganges, expected Binance-Chain-Nile" seed=8c379d4d3b9995c712665dc9a9414dbde5b30483@3.113.118.255:27146
E[2022-12-23|03:09:21.056] Couldn't connect to any seeds                module=p2p

**Comment by isaacyuno** [comment]
Hi there, what's your startup command? If you put config file folder somewhere, need to specify it. E.g. config folder with app.toml and config.toml is in path "./testnet/config", then your start command should be `bnbchaind start --home ./testnet &`

**Comment by sotatek-manhnguyen8** [comment]
@isaacyuno  Hello, I use command same with you. I put all config files at /data/config and start up command is `bnbchaind start --home /data &`

**Comment by isaacyuno** [comment]
Hi there, I have 
seed=9612b570bffebecca4776cb4512d08e252119005@3.114.127.147:27146
seed=7156d461742e2a1e569fd68426009c4194830c93@52.198.111.20:27146
seed=8c379d4d3b9995c712665dc9a9414dbde5b30483@3.113.118.255:27146
as my seeds and I could sync testnet correctly. I'm still suspecting that your config.toml and app.toml are not loaded correctly. Check your path again and also files in /data/config are correct? 
Did you see node_key.json  priv_validator_key.json in /data/config now?

**Comment by sotatek-manhnguyen8** [comment]
Yes, I use 3 above seeds like you, and when checking /data/config/, it have node_key and priv_validator_key.json too
```
root@bnb-test-0:/# ls -l /data/config/
total 64
-rw------- 1 root root    52 Dec 23 07:13 addrbook.json
-rw-r--r-- 1 root root  5804 Dec 23 06:59 app.toml
-rw-r--r-- 1 root root 13905 Dec 23 06:59 config.toml
-rw-r--r-- 1 root root 25870 Dec 23 06:59 genesis.json
-rw------- 1 root root   148 Dec 23 06:59 node_key.json
-rw------- 1 root root   345 Dec 23 06:59 priv_validator_key.json
```

**Comment by isaacyuno** [comment]
Your genesis.json size looks quite different from mine, what are first few lines of it?

**Comment by sotatek-manhnguyen8** [comment]
here are some first lines of it:
```
{
  "genesis_time": "2019-03-07T01:52:07.500913003Z",
  "chain_id": "Binance-Chain-Nile",
  "consensus_params": {
    "block_size": {
      "max_bytes": "1048576",
      "max_gas": "-1"
    },
    "evidence": {
      "max_age": "100000"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    }
  },
  ```

**Comment by isaacyuno** [comment]
It should be 
  "genesis_time": "2020-07-09T00:00:00.051674734Z",
  "chain_id": "Binance-Chain-Ganges",
  
  Could you get it from [testnet_config.zip](https://github.com/bnb-chain/node/releases/download/v0.10.4/testnet_config.zip) again?

**Comment by sotatek-manhnguyen8** [comment]
omg, I see and change like you said. It works like a charm now.
Much appreciate,  you save my day @isaacyuno
