### ISSUE TITLE
Firefox extension of Binance Wallet no longer works using Ledger Nano X as of today (2023-04-13)

### ISSUE THREAD

**Issue by derken** [bnb-chain/node#939]
The Binance Wallet Extension for firefox no longer works using Ledger Nano X as of today.
I'm guessing it's because of the upgrade of the BNB Beacon chain release 0.10.10 which was released today.

When trying to send BNB using the Binance Wallet Extension, it errors out with
  "LedgerClient: Call makeApp() first"

Same operation was working fine yesterday.

**Comment by ahymedDEV** [comment]
@derken Talk to Ledger Support on the [Ledger Live support](https://explore-ledger.online/) so that your issue can be looked into.

**Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by derken** [comment]
bnbcli still works properly with the binance chain ledger app so the problem is unlikely to be with https://github.com/bnb-chain/node or https://github.com/LedgerHQ/app-binance

The problem would seem to be in the firefox binance chain wallet extension (which doesn't appear to be open source)
https://www.bnbchain.org/en/binance-wallet
Apparently, it will no longer be maintained and will be merged into Trust Wallet

**Comment by ahymedDEV** [comment]
@derken create chat with the support i sent to you.

**Comment by derken** [comment]
Problem solved.

For future reference, in case someone lands here with the same problem.
It turns out  [Firefox 112](https://www.mozilla.org/en-US/firefox/112.0beta/releasenotes/) disabled the deprecated U2F JavaScript API by default which caused the Firefox Binance Wallet Extension to fail.

The U2F API can be re-enabled using the security.webauth.u2f preference in about:config as described in this article at Ledger
https://support.ledger.com/hc/en-us/articles/10371387758493?support=true
