### ISSUE TITLE
Unable to query staking rewards for delegator address

### ISSUE THREAD

**Issue by suggalla** [bnb-chain/node#955]
Hello, I'm not able to query the staking rewards for a delegator address. I've tried creating an ABCI query using the following paths: `abci_query?path="/custom/stake/rewards"` and  `abci_query?path="/store/stake_rewards/` and I'm not having any luck with either and I can't find documentation for this. Is there any way to query the delegator rewards from a full node? Thanks!

**Comment by ZiyuanStar** [comment]
You can get your reward address with your bsc address as below:
bnbcli staking cross-stake-info 0x992701c853301b120a6db0e4767aeecc737c515a --node http://dataseed2.defibit.io:80 --chain-id Binance-Chain-Tigris --side-chain-id bsc --trust-node

**Comment by suggalla** [comment]
> You can get your reward address with your bsc address as below: bnbcli staking cross-stake-info 0x992701c853301b120a6db0e4767aeecc737c515a --node http://dataseed2.defibit.io:80 --chain-id Binance-Chain-Tigris --side-chain-id bsc --trust-node

I only have my BNB address, do I need to convert it into a BSC address?
