### ISSUE TITLE
hardfork mainnet to 0.10.14 - error on replay

### ISSUE THREAD

**Issue by tmeinlschmidt** [bnb-chain/node#960]
hi,

unfortunately did the upgrade today, getting

    ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 083A426C37B5A5410E9F62148BE6397FA4381271903232AF5301351444DB64E0, got 6F21744580A9E0BF3B2ABB8DA3E899A20F74EB11FD142CED71F6897F7078DBF4

    I[2023-06-15|08:39:48.457] get last breathe block height                module=main height=321153415
    I[2023-06-15|08:39:48.457] reload latest snapshot                       module=statesync height=321153415
    I[2023-06-15|08:39:52.978] ABCI Handshake App Info                      module=consensus height=321213000 hash=083A426C37B5A5410E9F62148BE6397FA4381271903232AF5301351444DB64E0 software-version= protocol-version=0
    I[2023-06-15|08:39:52.978] ABCI Replay Blocks                           module=consensus appHeight=321213000 storeHeight=321213001 stateHeight=321213000
    I[2023-06-15|08:39:52.978] Replay last block using real app             module=consensus 
    I[2023-06-15|08:40:29.559] Starting ABCI with Tendermint                module=main 

is ther any way how to fix that w/o syncing from the scratch? Thanks

**Comment by nmiceli-simtlix** [comment]
Hi, 

My nodes are showing the same error:

`ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 083A426C37B5A5410E9F62148BE6397FA4381271903232AF5301351444DB64E0, got 6F21744580A9E0BF3B2ABB8DA3E899A20F74EB11FD142CED71F6897F7078DBF4`

**Comment by deepcrazy** [comment]
Hi there, Can you share some more logs also?

Also, Have you downloaded the new config and app.toml files using this: https://github.com/bnb-chain/node/releases/download/v0.10.14/mainnet_config.zip ?
If so, and if you first stopped the bnbchainid process and then restarted it, then still it shows this error? If so, Please share more logs and will check with team internally then.

**Comment by nmiceli-simtlix** [comment]
Yes. I have the latest config and app.toml files.



```
2023-06-15 19:12:29 | ERROR: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 083A426C37B5A5410E9F62148BE6397FA4381271903232AF5301351444DB64E0, got 6F21744580A9E0BF3B2ABB8DA3E899A20F74EB11FD142CED71F6897F7078DBF4 |  
-- | -- | --
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.877] Replay last block using real app             module=consensus |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.877] ABCI Replay Blocks                           module=consensus appHeight=321213000 storeHeight=321213001 stateHeight=321213000 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.877] ABCI Handshake App Info                      module=consensus height=321213000 hash=083A426C37B5A5410E9F62148BE6397FA4381271903232AF5301351444DB64E0 software-version= protocol-version=0 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.745] reload latest snapshot                       module=statesync height=321153415 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.745] get last breathe block height                module=main height=321153415 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.745] Loaded breathe block height                  module=dexkeeper height=321153415 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.745] Located day to load breathe block height     module=dexkeeper epochDay="CL\u0000\u0000\u0000\u0000\u0000\u0000" |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.095] No order comes in for the block              module=dexkeeper |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.095] replayed all tx. Starting match              module=dex height=321213000 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.095] Relaying block for order book                module=dex height=321213000 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.094] No order comes in for the block              module=dexkeeper |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.094] replayed all tx. Starting match              module=dex height=321212999 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.094] Relaying block for order book                module=dex height=321212999 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.094] No order comes in for the block              module=dexkeeper |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.094] replayed all tx. Starting match              module=dex height=321212998 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.094] Relaying block for order book                module=dex height=321212998 |  
  |   | 2023-06-15 19:12:29 | I[2023-06-15\|22:12:29.094] No order comes in for the block              module=dexkeeper
```

**Comment by tmeinlschmidt** [comment]
I'm on the same as @nmiceli-simtlix - updated `app.toml`, the only diff we do have in `config.json` is that we have
    state_sync_height = 0

**Comment by navidtadjalli** [comment]
Hey guys,

I faced the exact error
Is there any way to fix this issue?

**Comment by guagualvcha** [comment]
Please check this release: https://github.com/bnb-chain/node/releases/tag/v0.10.14, there is a hardfork few days ago.

**Comment by tmeinlschmidt** [comment]
@guagualvcha for sure, this issue is about THIS version

**Comment by nmiceli-simtlix** [comment]
Any updates on this issue?

**Comment by tmeinlschmidt** [comment]
as there's no progress, I managed to fix the node by reverting back to beginning of May (using zfs snapshots we do) and let it sync since then. Took a while, but works now

**Comment by nmiceli-simtlix** [comment]
@tmeinlschmidt you have your own snapshots or did you use public snapshots?

**Comment by tmeinlschmidt** [comment]
Own
