### ISSUE TITLE
No mention in release notes that new libc on Linux is needed

### ISSUE THREAD

**Issue by Crypto2** [bnb-chain/node#974]
Why is there no mention in the release notes that a new libc on Linux is needed? That's a jump from as old as Buster or even older to Bookworm on Debian for example with no notice.

**Comment by forcodedancing** [comment]
There is a note for libc for the old release https://github.com/bnb-chain/node/releases/tag/v0.10.5
We thought the node runners have such experience. Will add note in following releases, thanks.
