### ISSUE TITLE
Binance txn code

### ISSUE THREAD

**Issue by kiselev-sv** [bnb-chain/node#981]
The block 332616574 with two txn. External explorer  marks txn’s as  success. When we ask the node  0D6C985B7B6CBDE908B1514C6CA31EE867AF086C15CB76BD422896148FB02B00  field  code = 65539  we suppose, that txn is success, if code = 0. 

Kindly help us to understand what field code  in txn mean and what codes  we must explicit as success. In docs  the field describes as transaction result code

**Comment by deepcrazy** [comment]
Hi there, Can you provide more details or any screenshots what are you referring to exactly? Are you referring to Beacon chain?
And which docs you're referring to? Any link of it?

**Comment by kiselev-sv** [comment]
Sorry, no logs or snapshots...
Yes, I am about BNB (Beacon chain)
external explorer https://explorer.bnbchain.org/block/332616574
txn hash
https://explorer.bnbchain.org/tx/0D6C985B7B6CBDE908B1514C6CA31EE867AF086C15CB76BD422896148FB02B00
Docs describes result code
https://docs.bnbchain.org/docs/beaconchain/develop/api-reference/dex-api/paths#tx
code | integer | transaction result code | 0
What it means? Exactly

**Comment by deepcrazy** [comment]
`Code` defines the transaction's result if it success or not. Code: 0 means, it's success. I tried this API: https://dex-atlantic.binance.org/api/v1/tx/0D6C985B7B6CBDE908B1514C6CA31EE867AF086C15CB76BD422896148FB02B00
and got the following response:
```
{
    "code": 0,
    "data": "Tx{9D02F0625DEE0A5A2A2C87FA0A290A14BB791886E710AD6DF8D182713D840FE8F92FE14712110A08425553442D42443110E0ABB6C1A40112290A149AAB49E992D4217E03B4AAAB261D7E13884D38F112110A08425553442D42443110E0ABB6C1A40112730A26EB5AE987210218374DC89D77866331C965F33D4B0FF108EF81B717F0B8B961BE609CD77736BC12409900E871E8CD2CC22C1B7963B3324FBC39C332C21FFC66031EEA984CA86813B92605CDA4B97D8F868CF34BEA98F0307663BA7861BE1BF003F4F39DE646393ECB18C6C7B403208BFF071A46535741503A54484F522E52554E453A74686F7231756B776870676C7537796832673272773868376A7665653272306676306539306E79787636763A3338313036303030303030}",
    "hash": "0D6C985B7B6CBDE908B1514C6CA31EE867AF086C15CB76BD422896148FB02B00",
    "height": "332616574",
    "log": "Msg 0: ",
    "ok": true
}
```
which seems fine to me.

**Comment by kiselev-sv** [comment]
If my own node returns code 65539, what does it mean?
