### ISSUE TITLE
BNB node mainnet v0.10.16 wont sync from scratch

### ISSUE THREAD

**Issue by kiselev-sv** [bnb-chain/node#985]
Hello!
Cant start bnb beacon chain fullnode to sync on v0.10.16
many errors "connection established" - "dialing failed" - "stopping peer for error"

Empty base
Only 2 config files before starting
[configs.tar.gz](https://github.com/bnb-chain/node/files/12474248/configs.tar.gz)
[logzgz.tar.gz](https://github.com/bnb-chain/node/files/12474358/logzgz.tar.gz)

**Comment by VidalJilut** [comment]
Hello, have you resolve this isssues? 
can i help?

**Comment by kiselev-sv** [comment]
Hi! not solved, please help
can you look at my configs please? 
No progress, it says

binance-mainnet-3-node-1  | E[2023-09-07|07:43:10.500] Stopping peer for error                      module=p2p peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}" err=EOF
binance-mainnet-3-node-1  | I[2023-09-07|07:43:10.509] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:43:10.509] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:43:12.105] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:43:12.374] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | E[2023-09-07|07:43:40.149] Stopping peer for error                      module=p2p peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}" err=EOF
binance-mainnet-3-node-1  | I[2023-09-07|07:43:40.150] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:43:40.150] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | E[2023-09-07|07:43:40.168] connection with b7affdf084115fd7e7cdbc04686ef8c218e1801c@52.199.222.255:27146 has been established or dialed module=pex addr=b7affdf084115fd7e7cdbc04686ef8c218e1801c@52.199.222.255:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:43:40.168] connection with cfb5c1f7c10dfd99219158f5491ce65227bfd072@99.80.184.64:27146 has been established or dialed module=pex addr=cfb5c1f7c10dfd99219158f5491ce65227bfd072@99.80.184.64:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:43:40.168] connection with 48dada912ff10f04dec0db7900a78750384d06fd@52.31.30.219:27146 has been established or dialed module=pex addr=48dada912ff10f04dec0db7900a78750384d06fd@52.31.30.219:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:43:40.168] connection with c318936fc3005a07c332c282cd7c3f24fba0fb74@18.208.56.183:27146 has been established or dialed module=pex addr=c318936fc3005a07c332c282cd7c3f24fba0fb74@18.208.56.183:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:43:40.168] connection with dbec1c96777dc757db67945cbc41e3e793b94261@63.35.153.228:27146 has been established or dialed module=pex addr=dbec1c96777dc757db67945cbc41e3e793b94261@63.35.153.228:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:43:40.168] connection with 98579505572cc85488caa403bebb62e5b61d68e0@52.68.173.59:27146 has been established or dialed module=pex addr=98579505572cc85488caa403bebb62e5b61d68e0@52.68.173.59:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:43:40.168] connection with 5c96d4f0174dda7757bcda11a57ecc91851a90f0@52.73.6.125:27146 has been established or dialed module=pex addr=5c96d4f0174dda7757bcda11a57ecc91851a90f0@52.73.6.125:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:43:40.168] connection with e2acf608686f830386e8648d6fc2f50c3316aa88@13.113.112.169:27146 has been established or dialed module=pex addr=e2acf608686f830386e8648d6fc2f50c3316aa88@13.113.112.169:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:43:40.498] Stopping peer for error                      module=p2p peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}" err=EOF
binance-mainnet-3-node-1  | I[2023-09-07|07:43:40.509] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:43:40.509] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:43:42.108] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:43:42.372] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | E[2023-09-07|07:44:10.159] Stopping peer for error                      module=p2p peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}" err=EOF
binance-mainnet-3-node-1  | I[2023-09-07|07:44:10.169] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:44:10.169] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | E[2023-09-07|07:44:10.497] Stopping peer for error                      module=p2p peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}" err=EOF
binance-mainnet-3-node-1  | I[2023-09-07|07:44:10.498] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:44:10.498] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:44:12.118] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:44:12.371] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | E[2023-09-07|07:44:40.148] Stopping peer for error                      module=p2p peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}" err=EOF
binance-mainnet-3-node-1  | I[2023-09-07|07:44:40.158] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:44:40.158] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | E[2023-09-07|07:44:40.501] Stopping peer for error                      module=p2p peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}" err=EOF
binance-mainnet-3-node-1  | I[2023-09-07|07:44:40.502] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:44:40.502] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:44:42.106] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:44:42.375] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | E[2023-09-07|07:45:10.148] Stopping peer for error                      module=p2p peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}" err=EOF
binance-mainnet-3-node-1  | I[2023-09-07|07:45:10.158] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:45:10.158] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | E[2023-09-07|07:45:10.166] connection with e2c323d27867bad2298a5452490157436e70e698@52.213.118.150:27146 has been established or dialed module=pex addr=e2c323d27867bad2298a5452490157436e70e698@52.213.118.150:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:45:10.166] connection with b7affdf084115fd7e7cdbc04686ef8c218e1801c@52.199.222.255:27146 has been established or dialed module=pex addr=b7affdf084115fd7e7cdbc04686ef8c218e1801c@52.199.222.255:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:45:10.166] connection with ca1245471ff1f2224e1076dfd94d7d2d66077cf5@34.202.198.134:27146 has been established or dialed module=pex addr=ca1245471ff1f2224e1076dfd94d7d2d66077cf5@34.202.198.134:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:45:10.166] connection with 48dada912ff10f04dec0db7900a78750384d06fd@52.31.30.219:27146 has been established or dialed module=pex addr=48dada912ff10f04dec0db7900a78750384d06fd@52.31.30.219:27146
binance-mainnet-3-node-1  | E[2023-09-07|07:45:10.315] Stopping peer for error                      module=p2p peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}" err=EOF
binance-mainnet-3-node-1  | I[2023-09-07|07:45:10.326] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:45:10.326] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | E[2023-09-07|07:45:10.496] Stopping peer for error                      module=p2p peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}" err=EOF
binance-mainnet-3-node-1  | I[2023-09-07|07:45:10.497] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:45:10.497] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:45:12.107] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:45:12.275] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.227.165.88:27146} 289f680c0c78465dbf1d86c2260dd032d4541a4c out}"
binance-mainnet-3-node-1  | I[2023-09-07|07:45:12.370] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{34.247.169.233:27146} b323708b0bd429a95154ff0a287f0f42f432cb62 out}"
^Ccanceled

**Comment by toywar** [comment]
Hi, any updates with that problem?
