### ISSUE TITLE
All BNB testnet seed nodes are down

### ISSUE THREAD

**Issue by APshenkin** [bnb-chain/node#987]
https://docs.bnbchain.org/docs/rpc#testnet

[https://data-seed-pre-0-s1.bnbchain.org:443](https://data-seed-pre-0-s1.bnbchain.org/)
[https://data-seed-pre-1-s1.bnbchain.org:443](https://data-seed-pre-1-s1.bnbchain.org/)
[https://data-seed-pre-2-s1.bnbchain.org:443](https://data-seed-pre-2-s1.bnbchain.org/)
[https://data-seed-pre-0-s3.bnbchain.org:443](https://data-seed-pre-0-s3.bnbchain.org/)

All 4 nodes from documentation are not available. 

Is there any new hosts for them?

**Comment by asanikovich** [comment]
Tesnet DEX return 504 error
Please, check https://testnet-dex.binance.org/api/v1/fees
@HSG88 @forcodedancing @zjubfd

**Comment by mitter91** [comment]
right now list of seeds for testnets is not actual
`[2023-12-12|19:12:44.334] Error dialing seed                           module=p2p err="dial tcp 3.114.127.147:27146: connect: connection refused" seed=9612b570bffebecca4776cb4512d08e252119005@3.114.127.147:27146`
where we can find new hosts?

**Comment by forcodedancing** [comment]
> Tesnet DEX return 504 error Please, check https://testnet-dex.binance.org/api/v1/fees @HSG88 @forcodedancing @zjubfd

This should be fixed.

**Comment by forcodedancing** [comment]
> https://docs.bnbchain.org/docs/rpc#testnet
> 
> [https://data-seed-pre-0-s1.bnbchain.org:443](https://data-seed-pre-0-s1.bnbchain.org/) [https://data-seed-pre-1-s1.bnbchain.org:443](https://data-seed-pre-1-s1.bnbchain.org/) [https://data-seed-pre-2-s1.bnbchain.org:443](https://data-seed-pre-2-s1.bnbchain.org/) [https://data-seed-pre-0-s3.bnbchain.org:443](https://data-seed-pre-0-s3.bnbchain.org/)
> 
> All 4 nodes from documentation are not available.
> 
> Is there any new hosts for them?

Most of them should have recovered.

**Comment by forcodedancing** [comment]
> right now list of seeds for testnets is not actual `[2023-12-12|19:12:44.334] Error dialing seed module=p2p err="dial tcp 3.114.127.147:27146: connect: connection refused" seed=9612b570bffebecca4776cb4512d08e252119005@3.114.127.147:27146` where we can find new hosts?

@mitter91 Do you still face the same issue?

**Comment by mitter91** [comment]
@forcodedancing ofc, yes
is this seeds list still actual?
`seeds = "9612b570bffebecca4776cb4512d08e252119005@3.114.127.147:27146,8c379d4d3b9995c712665dc9a9414dbde5b30483@3.113.118.255:27146,7156d461742e2a1e569fd68426009c4194830c93@52.198.111.20:27146"
`

**Comment by forcodedancing** [comment]
> @forcodedancing ofc, yes is this seeds list still actual? `seeds = "9612b570bffebecca4776cb4512d08e252119005@3.114.127.147:27146,8c379d4d3b9995c712665dc9a9414dbde5b30483@3.113.118.255:27146,7156d461742e2a1e569fd68426009c4194830c93@52.198.111.20:27146" `

It is working now. Will close this issue. 
Please open another one if the issue happens again.
Thanks.
